CREATE TABLE IF NOT EXISTS feed_report_types (
  id BIGSERIAL PRIMARY KEY,
  key VARCHAR(64) NOT NULL,
  title VARCHAR(64) NOT NULL,
  description VARCHAR(256),
  level SMALLINT NOT NULL DEFAULT 0,
  position SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);