CREATE TABLE IF NOT EXISTS feed_posts (
  id BIGSERIAL PRIMARY KEY,
  uid BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  region_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  is_draft BOOLEAN NOT NULL DEFAULT FALSE,
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  visits_count INTEGER NOT NULL DEFAULT 0,
  reports_count INTEGER NOT NULL DEFAULT 0,
  votes_up_count INTEGER NOT NULL DEFAULT 0,
  votes_down_count INTEGER NOT NULL DEFAULT 0,
  title VARCHAR(128),
  slug VARCHAR(128),
  summary VARCHAR(256),
  article TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT uniq_posts_uid UNIQUE (uid),
  CONSTRAINT fk_feed_posts_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_feed_posts_region_id FOREIGN KEY (region_id) REFERENCES geo_regions(id) ON DELETE CASCADE,
  CONSTRAINT fk_feed_category FOREIGN KEY (category_id) REFERENCES feed_categories(id) ON DELETE CASCADE
);